### ISSUE TITLE
Using eslint-plugin-compat with babel-eslint

### ISSUE THREAD

**Issue by bencergazda** [amilajack/eslint-plugin-compat#220] opened 2019-04-08 10:46 UTC
Thank you for your really useful ESLint plugin. I have just see a question on [Stackoverflow](https://stackoverflow.com/questions/55386700/use-eslint-plugin-compat-alongside-babel), which started me thinking about how to make `eslint-plugin-compat` work with `babel-eslint`. 

At first it looks like `babel-eslint` makes `eslint-plugin-compat` unnecessary, as Babel transpiles the code to be compatible with specific browsers, but on the other hand, still there are useful hints from `eslint-plugin-compat` (like window.screenLeft() is not being supported in Firefox). My guess is that Babel isn't analyizing the code in this respect. Disqualifying eslint-plugin-compat would also skip these hints in my opinion, and this would be a pity.

Is there, or are you planning to create a lightweight rule configuration, which focuses only on what Babel cannot (or not intended to) transpile?

**Comment by amilajack** [comment] 2019-04-15 16:58
There's a difference between JS API's and browser APIs. Babel doesn't polyfill JS APIs. The solution for now is polyfilling APIs manually in the config. See the polyfilling section in the README. Closing as this is a duplicate of https://github.com/amilajack/eslint-plugin-compat/issues/174

**Closed by amilajack** 2019-04-15 16:58 UTC
