### ISSUE TITLE
Support for ESLint 9

### ISSUE THREAD

**Issue by u01jmg3** [amilajack/eslint-plugin-compat#614] opened 2024-04-06 14:47 UTC
https://github.com/amilajack/eslint-plugin-compat/blob/eba26a7f65c26774fcbc46185a0ca7c5bcdc309d/package.json#L117

https://github.com/eslint/eslint/releases/tag/v9.0.0

**Comment by herrherrmann** [comment] 2024-04-22 11:46
ESLint 9.0 also requires the flat config format, so this issue is probably kind of a duplicate of this older one? https://github.com/amilajack/eslint-plugin-compat/issues/603

**Comment by u01jmg3** [comment] 2024-04-22 22:22
Just need PR #609 to land. @amilajack can you help us out?

**Comment by nford88** [comment] 2024-05-23 15:42
> Just need PR #609 to land. @amilajack can you help us out?

The flat config ticket was merged yesterday!

**Comment by muuvmuuv** [comment] 2024-06-04 05:14
The next tag misses updated peerDependencies :)

**Comment by u01jmg3** [comment] 2024-06-11 10:13
Great work landing flat config file support 👏🏻

Will keep this issue open though because, as mentioned by @dargmuesli (https://github.com/amilajack/eslint-plugin-compat/pull/609#issuecomment-2123734301), this plugin doesn't fully support ESLint 9 due to the error: [context.getAncestors is not a function](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getancestors())

**Comment by u01jmg3** [comment] 2024-06-12 09:38
Thanks 🙏🏻, @dargmuesli - could this also be used with [eslint-plugin-escompat](https://github.com/keithamus/eslint-plugin-escompat)?

**Comment by dargmuesli** [comment] 2024-06-12 09:43
I think flat config must be supported.

**Comment by Mr0grog** [comment] 2024-07-01 15:49
Are there any specific fixes that could use some help here? Happy to donate some time this week if help is needed to move ESLint 9 support forward.

**Comment by dargmuesli** [comment] 2024-07-01 20:40
Great! 🥳 As mentioned

> currently this plugin doesn't fully support ESLint 9 due to the error: [context.getAncestors is not a function](https://eslint.org/blog/2023/09/preparing-custom-rules-eslint-v9/#context.getancestors())

There might be some follow up issues that surface after this issue is fixed, but I don't think there are many as the compat workaround I posted above works pretty flawlessly.

**Comment by Mr0grog** [comment] 2024-07-01 20:52
@dargmuesli that’s great, but mainly I’d like to hear from a maintainer what I can help do (or not help with). If maintainers are paying attention to ESLint v9 support, it’s not going to go very far just because I poke at it, and it’s not clear what they do or don’t need help with.

**Comment by brettz9** [comment] 2024-07-02 09:45
I've submitted #627 , a PR which should hopefully be a jump start on moving to ESLint 9 support. Hopefully someone can review and see if anything else needs to be done.

**Comment by sdavids** [comment] 2024-07-11 18:41
Maybe update the changelog as well?

**Comment by brettz9** [comment] 2024-07-11 21:35
Looks like releases are getting made, but despite having `@semantic-release/changelog` set up, the change log does not appear to be updating for whatever reason...

**Comment by brettz9** [comment] 2024-07-13 22:31
@amilajack : I think this can be closed now (by #627)

**Comment by brettz9** [comment] 2024-07-13 22:32
Thanks!

**Closed** 2024-07-13 22:31 UTC
