### ISSUE TITLE
Plugin does not work unless the file being linted is compiled with uglify

### ISSUE THREAD

**Issue by niftylettuce** [amilajack/eslint-plugin-compat#238] opened 2019-06-07 19:36 UTC
I have a large file that is a concatenation of a bunch of third party libraries.  Running `eslint` on it with `eslint-plugin-compat` doesn't report the same errors that occur when `uglify()` is run on the file.  Not sure how you'd like me to debug this or share code.

**Comment by amilajack** [comment] 2020-05-24 13:10
Duplicate of #102

**Closed by amilajack** 2020-05-24 13:10 UTC
