### ISSUE TITLE
Ignore feature detection

### ISSUE THREAD

**Issue by kirly-af** [amilajack/eslint-plugin-compat#271] opened 2019-10-17 13:48 UTC
We should have a way to do feature detection without disabling a rule.

A least one of theses examples should work with `"browserslist": ["cover 99.5%"]`:
```js
if (navigator.sendBeacon) {
}

if (navigator.sendBeacon != null) {
}

if (navigator.sendBeacon !== undefined) {
}

if (typeof navigator.sendBeacon !== 'undefined') {
}
```

**Comment by amilajack** [comment] 2019-12-25 21:11
Duplicate of https://github.com/amilajack/eslint-plugin-compat/issues/26

**Closed by amilajack** 2019-12-25 21:11 UTC
